web:
    image: gte451f/nginx
    volumes:
        - .:/var/www
        - ./docker/nginx/sites-available/default:/etc/nginx/sites-available/default
        - ./docker/nginx/fastcgi_params:/etc/nginx/fastcgi_params
        - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
        - "8080:80"
    links:
        - php

php:
  image: gte451f/php:5.6
  volumes:
        - .:/var/www
        - ./docker/file_storage:/file_storage/
        - ./docker/php5/fpm/php.ini:/etc/php5/fpm/php.ini
        - ./docker/php5/cli/php.ini:/etc/php5/cli/php.ini
        - ./docker/php5/php-fpm.conf:/etc/php5/fpm/php-fpm.conf
        - ./docker/php5/fpm/pool.d:/etc/php5/fpm/pool.d
  links:
    - db
db:
    image: mariadb:10.0.25
    volumes:
        - ./docker/mariadb:/etc/mysql/conf.d
        - ./docker/mariadb/data:/var/lib/mysql
    ports:
        - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: 0897r1q923yurf
        MYSQL_USER: api
        MYSQL_PASSWORD: api
        MYSQL_DATABASE: smores

